### ISSUE TITLE
How to import state machine cat API in your javascript

### ISSUE THREAD

**Issue by Jiajun-Deng** [Hades32/stama-visualizer#4]
Your project is cool and I'm doing a similar thing in javascript.
Currently I'm using angularJS and once I use 
`const smcat = require("state-machine-cat");` in my code the whole thing will break down. I'm curious how you import this API in your project.

**Comment by Hades32** [comment]
That's generally something you should ask at https://github.com/sverweij/state-machine-cat

But generally for a require to work the module has to be installed e.g. by npm install
